### ISSUE TITLE
Class 'XoopsModules/Wggallery/Helper' not found

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/wggallery#48]
Error: Class 'XoopsModules/Wggallery/Helper' not found in file /modules/wggalery/include/common.php line 32

XOOPS Version | XOOPS 2.5.11-Beta1
-- | --
PHP Version | 7.3.12
mySQL Version | 5.7.28
wggalery 1.14rc1

**Comment by ggoffy** [comment]
hi. 
"wggalery" can't be, the proper module name is "wggallery"  :)

**Comment by ggoffy** [comment]
when does this error appearing? installing? later?

**Comment by liomj** [comment]
After installing..

Sorry My mistake..issue can be close
