### ISSUE TITLE
Use of undefined constant _DC_WGGALLERY_AVAILABLE

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/wggallery#57]
Warning: Use of undefined constant _DC_WGGALLERY_AVAILABLE - assumed '_DC_WGGALLERY_AVAILABLE' (this will throw an Error in a future version of PHP) in file /modules/wggallery/class/Common/DirectoryChecker.php line 68

![image](https://user-images.githubusercontent.com/4613970/90424787-fbbb8500-e0be-11ea-84ed-0b656a54b0be.png)

**Comment by ggoffy** [comment]
done with update language files #58

thank you
