### ISSUE TITLE
Errors occured during uploading the images

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/wggallery#61]
Hi Goffy im currently testing Wggallery im having problem in uploading images
Errors occured during uploading the images
picture that i would like to upload is small in size but still failed

permission are set
my current setup, where else i can check where it might cause the problem ?

wgGallery 1.15 RC1 (07/01/2020)
XOOPS Version | XOOPS 2.5.11-Beta1
-- | --
PHP Version | 7.4.10
mySQL Version | 5.7.31

Minimum PHP required: 7.2 (your version is 7.4.10) 
MYSQL Minimum version required: 5.5 (your version is 5.7.31)
Minimum XOOPS required: 2.5.10 (your version is 2.5.11-Beta1) 
Minimum ModuleAdmin required: 1.1 (your version is 1.2) 

/home/xxx/public_html/uploads/wggallery ( The folder is Available) 
/home/xxx/public_html/uploads/wggallery/images/ ( The folder is Available) 
/home/xxx/public_html/uploads/wggallery/images/albums/ ( The folder is Available) 
/home/xxx/public_html/uploads/wggallery/images/original/ ( The folder is Available) 
/home/xxx/public_html/uploads/wggallery/images/large/ ( The folder is Available) 
/home/xxx/public_html/uploads/wggallery/images/medium/ ( The folder is Available) 
/home/xxx/public_html/uploads/wggallery/images/thumbs/ ( The folder is Available) 
/home/xxx/public_html/uploads/wggallery/images/watermarks/ ( The folder is Available)

**Comment by ggoffy** [comment]
hi. 
all images or only some?
did you make admin/maintainance/systemcheck?
are there any special characters (e.g. #+') in the file names? JS have sometimes problems with that.
if not, can you check the browser console whether there is a js-error?

**Comment by liomj** [comment]
Hi
i can't upload any images and no special character in the file name..

im just found out this in the chrome error console
```
fine-uploader.js:165 [Fine Uploader 5.13.0] Error when attempting to parse xhr response text (Unexpected token < in JSON at position 0) /fine-uploader/fine-uploader.js
Error uploading backdrop.jpg.  Reason: Upload failure reason unknown (wggallery/upload.php?op=list&alb_id=16)
DevTools failed to load SourceMap: Could not load content for media/fine-uploader/fine-uploader.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

btw i have successfully import all my images and album to wggallery

![Uploading Untitled.png…]()

**Comment by liomj** [comment]
![w](https://user-images.githubusercontent.com/16532279/94882100-9fa79700-0499-11eb-9e95-881e973c28b0.jpg)

**Comment by ggoffy** [comment]
hi. can you please try with another browser

**Comment by liomj** [comment]
I tried IE, Chrome, Edge & Firefox all failed to upload images

im also having the same issue in uploading multiple images in XOOPS image Manager

**Comment by ggoffy** [comment]
hi. tried it once more with current version from https://github.com/XOOPS/XoopsCore25 and current wggallery. upload is working without problems.
the problem seems to be the (invalid) token.
is there maybe a firewall which is blocking?
or does your server forbit transfer of header information?
otherwise we have to contact geekwright, he is more experienced with json token

**Comment by liomj** [comment]
i downloaded the latest xoops and wggallery from github same issue..no firewall is present

i just noticed im having the same issue with the multiple image upload function in image manager.. i will open up an issue in XOOPS Core..

**Comment by ggoffy** [comment]
ok, then I leave this issue open. Please give me feedback when and hwo you have solved the problem

**Comment by liomj** [comment]
i just upgraded the site from the latest xoops core commit

the multiupload still failed in image manager and wggallery..

.i tried to review the upload process in network xhr tab in google chrome console

in ajaxfineupload.php
i receive this error
Error: Call to undefined function mime_content_type()
https://pictr.com/images/2020/10/07/7hRCWQ.jpg

i guess this is my server issue and maybe can be close

btw is there any single upload available in wggallery ?

**Comment by ggoffy** [comment]
hi, no, there is no single file upload.

I'm still not sure whether function mime_content_type is the problem. The only place where I use it during upload procedure is when wgGallery is adding the watermark. Are you using watermarks? if yes, please deactivate it for testing and try again.

maybe you can also try somewhere "echo mime_content_type('test.php');"

**Comment by liomj** [comment]
watermark is not actiavted

i [ut this in theme
```
<{php}>
        echo mime_content_type('test.php'); <{/php}>
```
i received this Error : Error: Call to undefined function mime_content_type()

**Comment by cesagonchu** [comment]
mime_content_type() is obsolete, now you have to use finfo_file

https://www.php.net/manual/en/function.finfo-file.php

I saw that here:
https://forums.commentcamarche.net/forum/affich-33325024-probleme-avec-mime-content-type

**Comment by cesagonchu** [comment]
Ok, geekwright answered you here https://github.com/XOOPS/XoopsCore25/issues/888#issuecomment-705115771

**Comment by liomj** [comment]
hi thank you cesagonchu 

I just looked at the page for mime_content_type in the manual and it doesn't say it's deprecated! It even includes PHP 7 as a supported version of PHP
https://www.php.net/manual/en/function.mime-content-type.php

i have contacted to my service provider to check if mime_content_type and fileinfo is enable

**Comment by cesagonchu** [comment]
Ok :)
As I said before, I saw that here (in the comments):
https://forums.commentcamarche.net/forum/affich-33325024-probleme-avec-mime-content-type

**Comment by ggoffy** [comment]
hi liomj
if you want I can implement single file upload.

but whatever: you should try to solve the problem with the missing function, as it is used by the core, and maybe you miss also some other important functions from core, where till now no error occurs

**Comment by liomj** [comment]
hi goffy..that will great addition..more option for user 

Im still waiting for my provider reply, ill hope it will be solved once for all

**Comment by ggoffy** [comment]
hi. do you have got answer from your provider?

**Comment by liomj** [comment]
my government provided the hosting service but for technical part another third party is responsible for the server setup
unfortunately, i dont receive any reply from them :-(

i'll try follow up with them

by the way Goffy, thank you for adding the single and batch image upload feature
