### ISSUE TITLE
Call to undefined function XoopsModules\Wggallery\exif_read_data()

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/wggallery#65]
i tried to upload the single image and batch upload

Error : Error: Call to undefined function XoopsModules\Wggallery\exif_read_data()
Error: Error: Call to undefined function XoopsModules/Wggallery/exif_read_data() in file /modules/wggallery/class/ImagesHandler.php line 270

wgGallery 1.15 RC2
XOOPS Version XOOPS 2.5.11-Beta1
PHP Version 7.4.16
mySQL Version 5.7.34

**Comment by ggoffy** [comment]
do you have enabled the 'exif' extension in your php? If not please enabled it or deactivated the 'Save meta data (exif)' in module preferences.

**Comment by liomj** [comment]
Thank you solved the problem
