### ISSUE TITLE
no succesful cloning message

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/wggallery#66]
https://www.pictr.com/images/2021/04/22/7tJTEx.jpg
.cloning is successful after click the submit button but there is no successful cloning message 

wgGallery 1.15 RC2
XOOPS Version XOOPS 2.5.11-Beta1
PHP Version 7.4.16
mySQL Version 5.7.34

**Comment by ggoffy** [comment]
are you using an adapted template set in your theme for wggallery? maybe you have to replace the admin templates there

**Comment by liomj** [comment]
not using any any admin template  for wggallery

**Comment by liomj** [comment]
https://xoops.org/modules/newbb/viewtopic.php?post_id=365785#365785
