### ISSUE TITLE
chmod rights

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/wggallery#83]
I don't know if it's a problem with Xoops or the module but I have to log in as the ftp administrator to be able to modify the chmod in the uploads/wggallery folder. As a result, if a user is at a hosting company, he can't modify the chmods.

**Comment by ggoffy** [comment]
https://github.com/XoopsModules25x/wggallery/pull/86

if you start module update the rights should be set properly

**Comment by cesagonchu** [comment]
Ok, you got around the problem by pre-assigning the chmod to 777. It works, thank you! :)
