### ISSUE TITLE
For a better understanding, add directory modules/wggallery

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/wggallery#91]
Hi,
we get: 
[wggallery](https://github.com/XoopsModules25x/wggallery)/[extras](https://github.com/XoopsModules25x/wggallery/tree/master/extras)/[themes](https://github.com/XoopsModules25x/wggallery/tree/master/extras/themes)/xswatch4/

I think it's better to add a directory like this: 
wggallery/extras/themes/xswatch4/modules/wggallery

So, webmasters just copy wggallery to the xswatch4/modules/ directory.

No ?

**Comment by ggoffy** [comment]
yes and no

what, if someone is creating a clone of wggallery and call the clone "mygallery"

**Comment by alain01** [comment]
lol, ok ok ...
