### ISSUE TITLE
Order for albums

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/wggallery#92]
Hi ! 
We get a column "weight" but no input to change this value.

![Capture d’écran 2022-08-31 123922](https://user-images.githubusercontent.com/5336960/187660415-9d864cba-f764-4b6e-8722-b08ab24c6196.png)

**Comment by alain01** [comment]
Found ?
This ?
![tri-albums-wggallery](https://user-images.githubusercontent.com/5336960/187698888-5da9fe71-b898-48c5-8749-7ddb2643f124.png)

**Comment by alain01** [comment]
![Capture d’écran 2022-08-31 161835](https://user-images.githubusercontent.com/5336960/187701318-ddf1431d-7409-434c-8b80-959db4dd64ea.png)

**Comment by ggoffy** [comment]
hi
default sorting is "order by weight, id" therefore a value in weight is not mandatory for proper working

The idea of this module is, that all actions can be done on user side.
setting sort order should be done by drag&drop on user side. therefore there is no form field for entering the weight manually.

in this module admin area is only for showing and checking the inputs. 
If you want I can add a form field for the weight which is only visible on admin side, but I think this is not necessary.

**Comment by alain01** [comment]
No, it is not useful, but it was not easy to find the place to sort the collections and albums.
I understand the philosophy of putting the interface on the user side, no problem.
